// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCBFdEl6ZbXawMCCexSc5VwjCeMCgjueI',
    appId: '1:665271526560:web:416e1e3b04c50a7fa6d5c5',
    messagingSenderId: '665271526560',
    projectId: 'manticerp',
    authDomain: 'manticerp.firebaseapp.com',
    storageBucket: 'manticerp.firebasestorage.app',
    measurementId: 'G-M0X9R9N8B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7vDHrLRqwnpzzqi48ueChw3YMD0X4mXI',
    appId: '1:665271526560:android:ef324e9c6c7f2d42a6d5c5',
    messagingSenderId: '665271526560',
    projectId: 'manticerp',
    storageBucket: 'manticerp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR5fQX4ve6K5zu2Gm_hTU-2NFctlQ-5hg',
    appId: '1:665271526560:ios:6f854d76569345faa6d5c5',
    messagingSenderId: '665271526560',
    projectId: 'manticerp',
    storageBucket: 'manticerp.firebasestorage.app',
    androidClientId: '665271526560-0mubpnkk1ffll60ahqs7gsn1si9umala.apps.googleusercontent.com',
    iosClientId: '665271526560-n36dti832p36namr121jeu4o13ij60po.apps.googleusercontent.com',
    iosBundleId: 'com.manticerp.softronix',
  );
}
