import 'package:fpdart/fpdart.dart';
import '../../../../core/shared/shared_exports.dart';
import '../../accounts_exports.dart';

class CustomerRecievablesUsecase implements Usecase<dynamic, NoParams> {
  final IAccountsRepository repository;

  CustomerRecievablesUsecase({required this.repository});

  @override
  Future<Either<Failure, dynamic>> call(NoParams params) async {
    await Future.delayed(const Duration(seconds: 1));
    return right(<CustomerReceivableItemEntity>[
      const CustomerReceivableItemEntity(
        partyName: 'Ajwa KP Foods Bannu',
        location: 'Bannu',
        opening: 1000.00,
        openingIsDr: true,
        debit: 500.00,
        credit: 0,
        balance: 1500.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Al Majara Foods Pvt Ltd',
        location: 'Islamabad',
        opening: 761550.00,
        openingIsDr: true,
        debit: 0,
        credit: 150000.00,
        balance: 611550.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'AM Foods (Karachi)',
        location: 'Karachi',
        opening: 85640.00,
        openingIsDr: true,
        debit: 20000.00,
        credit: 0,
        balance: 105640.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Anees Brocker Karachi',
        location: 'Hyderabad',
        opening: 524285.19,
        openingIsDr: true,
        debit: 0,
        credit: 524285.19,
        balance: 0,
        balanceIsDr: false,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Darm Trading Company Doha',
        location: 'Doha Qatar',
        opening: 3179362.91,
        openingIsDr: true,
        debit: 500000.00,
        credit: 0,
        balance: 3679362.91,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Fauji Foods Limited',
        location: 'Islamabad',
        opening: 6553720.00,
        openingIsDr: true,
        debit: 0,
        credit: 1000000.00,
        balance: 5553720.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Gold Foods Multan',
        location: 'Multan',
        opening: 1098690.00,
        openingIsDr: true,
        debit: 250000.00,
        credit: 0,
        balance: 1348690.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Haji Bilal Khan',
        location: 'Quetta',
        opening: 1939655.74,
        openingIsDr: true,
        debit: 0,
        credit: 800000.00,
        balance: 1139655.74,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'King Choice Gmbh',
        location: 'Switzerland',
        opening: 58079436.21,
        openingIsDr: true,
        debit: 2000000.00,
        credit: 0,
        balance: 60079436.21,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Pepsico Int',
        location: 'Lahore',
        opening: 188707309.40,
        openingIsDr: true,
        debit: 0,
        credit: 50000000.00,
        balance: 138707309.40,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Rafhan Maize Products',
        location: 'Faisalabad',
        opening: 4320000.00,
        openingIsDr: true,
        debit: 750000.00,
        credit: 0,
        balance: 5070000.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'National Foods Ltd',
        location: 'Karachi',
        opening: 2175000.00,
        openingIsDr: true,
        debit: 0,
        credit: 500000.00,
        balance: 1675000.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Shan Foods Pvt Ltd',
        location: 'Karachi',
        opening: 980500.00,
        openingIsDr: true,
        debit: 320000.00,
        credit: 0,
        balance: 1300500.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Engro Foods Ltd',
        location: 'Karachi',
        opening: 12450000.00,
        openingIsDr: true,
        debit: 0,
        credit: 2000000.00,
        balance: 10450000.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Nestle Pakistan Ltd',
        location: 'Lahore',
        opening: 33750000.00,
        openingIsDr: true,
        debit: 5000000.00,
        credit: 0,
        balance: 38750000.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Hilal Confectionery',
        location: 'Karachi',
        opening: 675400.00,
        openingIsDr: true,
        debit: 0,
        credit: 675400.00,
        balance: 0,
        balanceIsDr: false,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Mitchell\'s Fruit Farms',
        location: 'Lahore',
        opening: 1540000.00,
        openingIsDr: true,
        debit: 180000.00,
        credit: 0,
        balance: 1720000.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Dawn Bread Pvt Ltd',
        location: 'Karachi',
        opening: 880000.00,
        openingIsDr: true,
        debit: 0,
        credit: 300000.00,
        balance: 580000.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Menu Foods Rawalpindi',
        location: 'Rawalpindi',
        opening: 2230000.00,
        openingIsDr: true,
        debit: 450000.00,
        credit: 0,
        balance: 2680000.00,
        balanceIsDr: true,
      ),
      const CustomerReceivableItemEntity(
        partyName: 'Shezan International',
        location: 'Lahore',
        opening: 3100000.00,
        openingIsDr: true,
        debit: 0,
        credit: 1200000.00,
        balance: 1900000.00,
        balanceIsDr: true,
      ),
    ]);
  }
}
