import 'dart:io';
import 'package:mason/mason.dart';
import 'package:path/path.dart' as path;

// ---------------------------------------------------------------------------
// export_generator
//
// Regenerates per-feature export barrels ({feature}_exports.dart).
//
// What it does:
//   - If feature_name is given  → updates only that feature's barrel
//   - If feature_name is empty  → scans lib/features/ and updates all features
//
// Each barrel gets:
//   1. export '../../../../app_exports.dart'  (core re-export)
//   2. export for every .dart file inside the feature EXCEPT:
//        - the barrel file itself  ({feature}_exports.dart)
//        - generated files         (*.g.dart, *.freezed.dart)
//        - view files              (presentation/*/views/*.dart)
//          └─ views import the barrel, so exporting them would be circular
// ---------------------------------------------------------------------------

Future<void> run(HookContext context) async {
  final logger = context.logger;
  final featureNameInput = (context.vars['feature_name'] as String).trim();

  final featuresDir = Directory('lib/features');
  if (!featuresDir.existsSync()) {
    logger.err('lib/features/ not found. Run from your Flutter project root.');
    return;
  }

  // Determine which features to process
  final featuresToProcess = <String>[];

  if (featureNameInput.isEmpty) {
    for (final entity in featuresDir.listSync()) {
      if (entity is Directory) {
        featuresToProcess.add(path.basename(entity.path));
      }
    }
    logger.info(
      '\n📦 Updating exports for ${featuresToProcess.length} feature(s)...\n',
    );
  } else {
    featuresToProcess.add(_toSnakeCase(featureNameInput));
  }

  for (final featureFile in featuresToProcess) {
    _updateFeatureBarrel(featuresDir, featureFile, logger);
  }

  logger.success('\n✅ Feature export barrels updated!');
}

// ---------------------------------------------------------------------------
// Regenerate {feature}_exports.dart for a single feature
// ---------------------------------------------------------------------------
void _updateFeatureBarrel(
  Directory featuresDir,
  String featureFile,
  Logger logger,
) {
  final featureDir = Directory('${featuresDir.path}/$featureFile');
  if (!featureDir.existsSync()) {
    logger.warn('⚠️  Feature "$featureFile" not found. Skipping.');
    return;
  }

  final barrelFileName = '${featureFile}_exports.dart';
  final barrelFile = File('${featureDir.path}/$barrelFileName');

  // ── Collect files to export ───────────────────────────────────────────────
  final toExport = <String>[];
  final viewPattern = RegExp(r'presentation/[^/]+/views/');

  for (final entity in featureDir.listSync(recursive: true)) {
    if (entity is! File) continue;

    final normalised = entity.path.replaceAll(r'\', '/');
    if (!normalised.endsWith('.dart')) continue;

    final relative = path
        .relative(normalised, from: featureDir.path.replaceAll(r'\', '/'))
        .replaceAll(r'\', '/');

    if (relative == barrelFileName) continue;           // barrel itself
    if (relative.endsWith('.g.dart')) continue;         // generated
    if (relative.endsWith('.freezed.dart')) continue;   // generated
    if (viewPattern.hasMatch(relative)) continue;       // views (circular risk)

    toExport.add(relative);
  }

  toExport.sort();

  // ── Write barrel ──────────────────────────────────────────────────────────
  final buffer = StringBuffer()
    ..writeln('// ${_toPascalCase(featureFile)} Feature Exports')
    ..writeln('// Generated by export_generator — do not edit manually')
    ..writeln()
    ..writeln('// Core exports')
    ..writeln("export '../../../../app_exports.dart';")
    ..writeln()
    ..writeln('// Feature files');

  for (final file in toExport) {
    buffer.writeln("export './$file';");
  }

  barrelFile.writeAsStringSync(buffer.toString());

  logger.success(
    '📦 Updated: lib/features/$featureFile/$barrelFileName '
    '(${toExport.length} file export(s))',
  );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
String _toSnakeCase(String text) {
  return text
      .replaceAllMapped(RegExp(r'[A-Z]'), (match) => '_${match.group(0)}')
      .toLowerCase()
      .replaceAll(RegExp(r'^_'), '');
}

String _toPascalCase(String text) {
  return text.split('_').map((word) {
    if (word.isEmpty) return '';
    return word[0].toUpperCase() + word.substring(1).toLowerCase();
  }).join('');
}
